### ISSUE TITLE
Celery tasks started failing  

### ISSUE THREAD

**Issue by luabida** [osl-incubator/satellite-weather-downloader#11]
![image](https://user-images.githubusercontent.com/82233055/206444703-db889272-5d46-47ee-b1c1-edbf76367094.png)

**Comment by luabida** [comment]
![image](https://user-images.githubusercontent.com/82233055/206446271-9a00ba5e-d670-4848-88aa-2c0a9926ce93.png)
apparently, python is corrupting the txt file
@xmnlab can you think on a better way of doing this?

**Comment by xmnlab** [comment]
it looks like a binary file .. maybe it is writing the data using the binary format by chance?

**Comment by luabida** [comment]
It shouldn't, it is suppose to only change `false` to `true`

**Comment by xmnlab** [comment]
Could you share the code you are using  ?

**Comment by luabida** [comment]
Sure
```
    def gen_next_date() -> str:
        """
        Open backfill file and search for next available date.
        Returns the next date set as False and change it to True.
        """
        file = Path(BACKFILL_FILE)

        with open(file, 'r', encoding='utf-8') as f:
            data = f.readlines()

        for i, line in enumerate(data):
            flag = 'false' #False = not uploaded

            if flag in line:
                date, flag = line.split(' ')
                data[i] = line.replace('false', 'true')

                with open(file, 'w', encoding='utf-8') as f:
                    for line in data:
                        f.write(line)
                
                yield date
    
    try:
        date = next(gen_next_date())
```

**Comment by luabida** [comment]
@xmnlab I'm thinking on create a db similar to what ttracker does, with a simple `.backfill.db` shared file to replace the .txt file

**Comment by xmnlab** [comment]
Could you share the code you are using  ?

**Comment by xmnlab** [comment]
I don't know the context .. so it is hard to me to give you any feedback XD

**Comment by luabida** [comment]
Another issue:
```
Arguments: {'hostname': 'celery@ac8f5b845df5', 'id': '37e77caf-04b8-48c6-9e0d-697bd091ba9c', 'name': 'fetch_brasil_weather', 'exc': "OperationalError('database is locked')", 'traceback': 'Traceback (most recent call last):\n  File "/opt/conda/envs/env-satellite/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File "/opt/conda/envs/env-satellite/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/services/satellite_weather_downloader/celery_app/tasks.py", line 198, in reanalysis_fetch_brasil_data\n    fetch_weather(\'fetch_brasil_weather\', \'copernicus_br\')\n  File "/opt/conda/envs/env-satellite/lib/python3.11/site-packages/celery/local.py", line 188, in __call__\n    return self._get_current_object()(*a, **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/conda/envs/env-satellite/lib/python3.11/site-packages/celery/app/trace.py", line 735, in __protected_call__\n    return orig(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/conda/envs/env-satellite/lib/python3.11/site-packages/celery/app/task.py", line 392, in __call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/services/satellite_weather_downloader/celery_app/tasks.py", line 150, in fetch_weather\n    date = db.next_date()\n           ^^^^^^^^^^^^^^\n  File "/opt/services/satellite_weather_downloader/celery_app/backfill.py", line 143, in next_date\n    cur.execute(f\'UPDATE {self.tablename}\'\nsqlite3.OperationalError: database is locked\n', 'args': '[]', 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
```

**Comment by xmnlab** [comment]
As you can see, the latest error is: the database is locked. It looks like multiple processes or threads are trying to update the sqlite file. So in this case, the way to go would be move to a database that handles parallel access/modification.
